import { readFileSync, writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'

const root = new URL('../', import.meta.url)
const read = (name) => readFileSync(new URL(name, root), 'utf8')

const stripModuleSyntax = (source, label) => {
  const stripped = source
    .replace(/^\s*import\s[\s\S]*?from\s*['"][^'"]+['"]\s*;?[ \t]*$/gm, '')
    .replace(/^export\s+/gm, '')
  if (/^[ \t]*(import|export)\s/m.test(stripped)) {
    throw new Error(`${label}: module syntax survived inlining; extend stripModuleSyntax`)
  }
  return stripped.trim()
}

// The harness ships these as browser platform singletons, so the bundle asks for
// them by name instead of bundling a copy.
const PROVIDED = ['react', '@deepseek-ai/dsh-client-ui-primitives']

const MODULES = ['src/hold.js', 'src/i18n.js', 'src/client.js']

export const buildClientBundle = () => {
  const pkg = JSON.parse(read('package.json'))
  const inlined = MODULES.map((name) => stripModuleSyntax(read(name), name)).join('\n\n')

  // dsh 0.1.7 renamed the size-suffixed icon primitives to weight-suffixed ones
  // (IconSendOutline14 -> IconSendOutlineRegular). Alias only when the legacy name is
  // absent, so one bundle keeps working on both a 0.1.5 and a 0.1.7 host.
  const provided = [
    `    const React = require('react')`,
    `    const hostPrimitives = require('@deepseek-ai/dsh-client-ui-primitives')`,
    `    const primitives = { ...hostPrimitives }`,
    `    const RENAMED_ICONS = {`,
    `      IconChevronDownOutline14: 'IconChevronDownOutlineRegular',`,
    `      IconChevronLeftOutline14: 'IconChevronLeftOutlineRegular',`,
    `      IconChevronRightOutline14: 'IconChevronRightOutlineRegular',`,
    `      IconChevronUpOutline14: 'IconChevronUpOutlineRegular',`,
    `      IconEditOutline16: 'IconEditOutlineRegular',`,
    `      IconQueueOutline14: 'IconQueueOutlineRegular',`,
    `      IconSendOutline14: 'IconSendOutlineRegular',`,
    `      IconTrashOutline16: 'IconTrashOutlineRegular',`,
    `    }`,
    `    for (const [legacy, current] of Object.entries(RENAMED_ICONS)) {`,
    `      if (primitives[legacy] === undefined && hostPrimitives[current] !== undefined) primitives[legacy] = hostPrimitives[current]`,
    `    }`,
  ].join('\n')

  return `/* GENERATED by scripts/build-client.mjs - do not edit. */
window.__ModuleLoader__.load({
  id: '${pkg.name}',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports

${provided}

    var plugin = (() => {
${inlined}

      return { inject, apply }
    })()

    exports.apply = plugin.apply
    exports.inject = plugin.inject
    return module.exports
  },
})
`
}

export const PROVIDED_MODULES = PROVIDED

const isEntryPoint = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href

if (isEntryPoint) {
  writeFileSync(new URL('client.js', root), buildClientBundle())
  console.log('[hold] built client.js')
}
